pages_build_output_dir = ".vercel/output/static"
name = "lianmin-status"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "lianmin-uptime"
database_id = "8fe1dd1e-aba1-466a-a67d-95d90168a01c"

